config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :follow, :follower] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'search' => 'searchs#search'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    book_comment = book.book_comments.build(book_comment_params)
    book_comment.user_id = current_user.id
    book_comment.save
    @book_comments = book.book_comments
    render :index
  end

  def destroy
    book_comment = BookComment.find(params[:id])
    @book_comments = book_comment.book.book_comments
    book_comment.destroy
    render :index
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment, :book_id, :user_id)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
 <table class="table table-hover table-inverse">
<tbody>
  <% book_comments.each do |comments| %>
  <% unless comments.id.nil? %>
    <tr>
      <td>
        <%= link_to user_path(comments.user.id) do %>
        　<%= attachment_image_tag comments.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
        <% end %>
        <br><%= link_to "#{comments.user.name}", user_path(comments.user.id) %></br>
      </td>
      <td>
        <%= comments.comment %>
      </td>
      <td>
        <% if comments.user == current_user %>
        <div class="comment_delete">
        　<%= link_to "destroy", book_book_comment_path(comments.book_id, comments.id), method: :delete, remote: true %>
        </div>
        <% end %>
      </td>
    </tr>
  <% end %>
  <% end %>
</tbody>
 </table>

app/views/book_comments/_form.html.erb
 <%= form_with model: [book, book_comment], url: book_book_comments_path(book.id) do |f| %>
    <table class=="table table-hover table-inverse">
      <tbody>
        <tr>
          <%= f.text_area :comment, rows: '5',placeholder: "コメントをここに" ,class:"input-mysize" %>
          <%= f.submit "送信", class:"btn btn-outline-dark comment-submit float-raght" %>
        </tr>
      </tbody>
    </table>
 <% end %>

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'book_comments/comment', { book_comments: @book_comments}) %>")
$("textarea").val('')