config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :follow, :follower] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'search' => 'searchs#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :relationships, foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id',dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

   def following?(other_user)
    self.followings.include?(other_user)
   end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def self.search(search,word)
    if search == "forward_match"
                     @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                     @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                     @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
                     @user = User.where("name LIKE?","%#{word}%")
    else
                     @user = User.all
    end
  end

  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book=Book.new
    @user = current_user
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all

  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
  <h2>User info</h2>
   <p><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
   <table class="table">
       <tbody>
           <tr>
               <th>name</th>
               <th class="profile-name"><%= user.name %></th>
            </tr>
            <tr>
               <th>introduction</th>
               <td><%= user.introduction %></td>
            </tr>
            <tr>
                <th>Follows</th>
                <td><%= link_to @user.followings.count, followings_user_path(@user.id) %></td>
            </tr>
            <tr>
                <th>Followers</th>
                <td><%= link_to @user.followers.count, followers_user_path(@user.id) %></td>
            </tr>
            <tr>
                <th></th>
                <th>
                 <% unless current_user == user %>
                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block btn-position' %>
                     <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, user.id %>
                      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block btn-position' %>
                     <% end %>
                  <% end %>
                <% end %>
               </th>
            </tr>
        </tbody>
    </table>
  <div class="row">
    <%= link_to '', edit_user_path(user), class: "fas fa-user-cog btn-i-edit btn-outline-secondary btn-block" %>
  </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div id="error_explanation">
     <% if @user.errors.any? %>
    <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @user.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-5 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <p><label for="inputName">Name</label></p>
      <p><%= f.text_field :name,class:"form-control form-group", autofocus: true, id:"inputName", placeholder:"名前" %></p>
      <p><label for="inputImage">Image</label></P>
      <p><%= f.attachment_field :profile_image, class:"input-profile-image" %></p>
      <p><label for="inputIntroduction">introduction</label></p>
      <p><%= f.text_field :introduction,class:"form-control form-group", autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文" %></p>
      <%= f.submit "Update User", class:"btn-edit" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px5 px-sm-0">
    <div class="row">
        <div class="col-md-12 offset-md-1">
          <p></p>
          <h2>Follower Users</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.followings.count %></td>
                  <td>フォロワー数:<%= user.followers.count %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                 </tr>
                <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/followings.html.erb
<div class="container px5 px-sm-0">
    <div class="row">
        <div class="col-md-12 offset-md-1">
          <p></p>
          <h2>Follow Users</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                  <td><%= user.name %></td>
                  <td>フォロー数:<%= user.followings.count %></td>
                  <td>フォロワー数:<%= user.followers.count %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                </tr>
                <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  　<div id="error_explanation">
   <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: current_user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Users</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %></td>
                   <td>
                 <% unless current_user == user %>
                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: '' %>
                     <% end %>
                  <% else %>
                    <%= form_for(current_user.relationships.build) do |f| %>
                      <%= hidden_field_tag :follow_id, user.id %>
                      <%= f.submit 'フォローする', class: '' %>
                     <% end %>
                  <% end %>
                <% end %>
               </td>
              </tr>
      <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: @user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @books.each do |books| %>
              <tr>
                <td>
                  <%= link_to user_path(books.user) do %>
                    <%= attachment_image_tag books.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%=link_to books.title, book_path(books) %></td>
                <td><%= books.body %></td>
                <td><%= link_to "コメント数:#{books.book_comments.count}", book_path(books.id) %></td>
              </tr>
      <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>