config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :follow, :follower] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'search' => 'searchs#search'
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    # favorites.where(user_id: user.id).exists?
    puts user
    puts favorites.where(user_id: user.id).exists?
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
                    @book = Book.where("title LIKE?","%#{word}")
    elsif search == "backward_match"
                    @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
                    @book = Book.where("#{word}")
    elsif search == "partial_match"
                    @book = Book.where("title LIKE?","%#{word}%")
    else
                    @book = Book.all
    end
  end


  validates :title, presence: true
  validates :body, length: {maximum: 200,minimum: 1}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book), notice: 'You have created book successfully.'
      else
        @user = current_user
        @books = Book.all
        render :index
      end
  end

  def index
    to = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @books = Kaminari.paginate_array(books).page(params[:page]).per(8)
    @user = current_user
    @book = Book.new
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def show
    @book_find = Book.find(params[:id])
    @user = @book_find.user
    @book = Book.new
    @users = User.all
    @book_comment = BookComment.new
    @book_comments = @book_find.book_comments
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
 end

  private

    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
    <h2>New book</h2>
    <%= form_with model:book, local:true do |f| %>
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control form-group"%>
      <label for= "book_body">Opinion</label>
      <%= f.text_area :body, class: "form-control form-group" %>
      <%= f.submit 'Create Book', class: "btn btn-success"  %>
        
    <% end %>

app/views/books/edit.html.erb
book.edit
<p id="notice"></p>
<div class="container">

     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-5 mx-auto">
      <h2>Editing Book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <p><label for="inputName">Title</label></p>
        <p><%= f.text_field :title, class:"form-control form-group",autofocus: true, id:"inputTitle", placeholder:"タイトル" %></p>
        <p><label for="inputOpinion">Opinion</label></p>
        <p><%= f.text_field :body, class:"form-control form-group",autofocus: true, id:"inputBody", placeholder:"Opinion" %></p>
      <%= f.submit "Update Book", class:"btn" %></br>
      <% end %>
      <p></p>
      <span><%= link_to "Show", book_path(@book), class: 'btn btn-sm btn-success' %></span>
      <span>|</span>
      <span><%= link_to "Back", books_path, class: 'btn btn-sm btn-success' %></span>
    </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: current_user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thread>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thread>
            <tbody>
      <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title ,book_path(book) %></td>
                <td><%= book.body %></td>
                  <td id="favorite-btn_<%= book.id %>">
                    <%= render 'favorites/favorite-btn', book: book %>
                  </td>
                <td><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></td>
              </tr>
      <% end %>
            </tbody>
          </table>
          <%= paginate @books %>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px5 px-sm-0">
  <div id="error_explanation">
     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
    <% end %>
    <% end %>
    </div>
    <div class="row">
        <div class= "col-md-3">
            <p><%= render 'users/info', user: @user %></p>
            <p><%= render 'books/list', book: @book %></P>
        </div>
        <div class="col-md-8 offset-md-1">
          <p></p>
          <h2>Book detail</h2>
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @book_find.user, :profile_image, size:"40x40", fallback: "no_image.jpg" %>
                  <% end %>
                  <br><%= link_to @user.name, user_path(@user) %></br>
                </td>
                <td><%= link_to @book_find.title, book_path(@book_find.id) %></td>
                <td><%= @book_find.body %></td>
                <td id="favorite-btn_<%= @book_find.id %>">
                  <%= render 'favorites/favorite-btn', book: @book_find %>
                </td>
                <td>コメント件数:<%= @book_find.book_comments.count %></td>
                <% if @user.id == current_user.id %>
                  <td><%= link_to "Edit", edit_book_path(@book_find.id) %></td>
                  <td><%= link_to "Destroy", book_path(@book_find.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
　　　　　<h4><strong>コメント</strong></h4>

          <div id="comments_area">
            <%= render partial: 'book_comments/comment', locals: { book_comments: @book_comments,user: @user } %>
          </div>
          <% if user_signed_in? %>
          <div id="comments_create">
            <%= render partial: 'book_comments/form', locals: { book_comment: @book_comment,book: @book_find } %>
          </div>
          <% end %>
        </div>
    </div>
  </div>