config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index, :follow, :follower] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get 'search' => 'searchs#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    # favorites.where(user_id: user.id).exists?
    puts user
    puts favorites.where(user_id: user.id).exists?
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
                    @book = Book.where("title LIKE?","%#{word}")
    elsif search == "backward_match"
                    @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
                    @book = Book.where("#{word}")
    elsif search == "partial_match"
                    @book = Book.where("title LIKE?","%#{word}%")
    else
                    @book = Book.all
    end
  end


  validates :title, presence: true
  validates :body, length: {maximum: 200,minimum: 1}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :relationships, foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id',dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

   def following?(other_user)
    self.followings.include?(other_user)
   end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def self.search(search,word)
    if search == "forward_match"
                     @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                     @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                     @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
                     @user = User.where("name LIKE?","%#{word}%")
    else
                     @user = User.all
    end
  end

  validates :name, length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!,except: [:top, :about]


      def after_sign_in_path_for(resource)
      user_path(resource)
      end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book), notice: 'You have created book successfully.'
      else
        @user = current_user
        @books = Book.all
        render :index
      end
  end

  def index
    to = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @books = Kaminari.paginate_array(books).page(params[:page]).per(8)
    @user = current_user
    @book = Book.new
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def show
    @book_find = Book.find(params[:id])
    @user = @book_find.user
    @book = Book.new
    @users = User.all
    @book_comment = BookComment.new
    @book_comments = @book_find.book_comments
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
 end

  private

    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.build(book_id: params[:book_id])
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]

    if @range == '1'
      @user = User.search(search,word)
    else
      @book = Book.search(search,word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book=Book.new
    @user = current_user
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all

  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white pt-1 pb-1">
      <nav class="navbar navbar-expand-lg navbar-light navbar-white">
        <div class="container">
          <h2><%= link_to "Bookers", root_path, class: 'text-white'%></h2>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li>
              <i class="fas fa-home"></i><%= link_to 'Home', user_path(id: current_user), class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
             <i class="fas fa-users"></i><%= link_to 'Users', users_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
             <li>
              <i class="fas fa-book-open"></i><%= link_to 'Books', books_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-sign-out-alt"></i><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <% else %>
             <li>
               <i class="fas fa-home" ></i><%= link_to 'Home', root_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
             <li>
              <i class="fas fa-link" ></i><%= link_to 'About', home_about_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-user-plus"></i><%= link_to "sign up", new_user_registration_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <li>
              <i class="fas fa-sign-in-alt"></i><%= link_to "login", new_user_session_path, class: 'd-inline-block nav-link text-white ml-1 font-weight-bold' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div class="search">
        <p></p>
        <% if user_signed_in? %>
         <%= form_tag(search_path, method: :get) do %>
            <%= text_field_tag (:word) %>
            <%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User' , '1'], ['Book', '2']]) %>
            <%= select_tag 'search', options_for_select([["前方一致","forward_match"],["後方一致", "backward_match"], ["完全一致","perfect_match"],['部分一致','partrial_match']]) %>
            <%= submit_tag '検索' %>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>